### ISSUE TITLE
Aprire issue per pagine da tradurre

### ISSUE THREAD

**Issue by garak** [garak/symfony-docs-it#221]
Cercare tutte le pagine attualmente quasi vuote (contengono solo il titolo e la stringa "TODO da tradurre") e apire una issue per ogni pagina. Sul branch 2.7

**Comment by DavidePastore** [comment]
Fatto in #223, #224, #225, #226, #227, #228 e #229.

**Comment by garak** [comment]
Grazie @DavidePastore !
