### ISSUE TITLE
Ipotesi per la gestione dell'aggiornamento delle traduzioni

### ISSUE THREAD

**Issue by lucasaba** [garak/symfony-docs-it#83]
Stato vedendo che è possibile inserire [commenti nei file rst](http://docutils.sourceforge.net/docs/user/rst/quickref.html#comments).

Sarebbe possibile inserire un commento nella traduzione con il commit del file originale a cui fa riferimento in modo che lo script usi git/github per aggiornarci sulle traduzioni ?

``` rst
.. 030a6f8672
   index::
   single: Emails; Testing
```

Non dovrebbe creare problemi e ne risolverebbe diversi.

**Comment by garak** [comment]
Chiudo perché ormai il repo è abbandonato. Grazie comunque.
